language: generic
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.29.2
  


before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

deploy:
  provider: script
  script:
    - chmod -R 777 .
    - sh deploy.sh
  on:
    branch: master

code_climate:
  secure: $CODE_CLIMATE_TOKEN