language: generic
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.29.2
  


before_deploy:
  - quasar build

deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "${AWS_CLIENT_BUCKET}"
  skip_cleanup: true
  local_dir: client/dist/spa
  on: 
    branch: master

code_climate:
  secure: "${CODE_CLIMATE_TOKEN}"