version: "3.8"
   
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: $SQL_USER
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_DB: $SQL_DATABASE

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
  